[package]
name = "rmig"
version = "0.0.1"
authors = ["Brian Seymour <b@bri.io>"]
edition = "2018"

[dependencies]
text_io = "0.1.8"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.45"
