[package]
name = "rmig"
version = "0.0.1"
authors = ["Brian Seymour <b@bri.io>"]
edition = "2018"

[dependencies]
mysql = "*"
text_io = "0.1.8"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.45"
termion = "*"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
